name: FlyPlugin
version: '${project.version}'
main: me.zhichgaming.flyplugin.FlyPlugin
api-version: 1.8.8
authors: [ ZhichGaming ]
description: Allows a player to fly.
commands:
  fly:
    description: Allows you to fly.
    usage: /<command>
